// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionTorneos.API.Migrations
{
    [DbContext(typeof(TorneosAPIContext))]
    partial class TorneosAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionTorneos.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEquipo"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEquipo");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("GestionTorneos.EventoJugador", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvento"));

                    b.Property<int>("IdJugador")
                        .HasColumnType("integer");

                    b.Property<int>("IdPartido")
                        .HasColumnType("integer");

                    b.Property<int?>("JugadorIdJugador")
                        .HasColumnType("integer");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer");

                    b.Property<int?>("PartidoIdPartido")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEvento");

                    b.HasIndex("JugadorIdJugador");

                    b.HasIndex("PartidoIdPartido");

                    b.ToTable("EventosJugadores");
                });

            modelBuilder.Entity("GestionTorneos.Jugador", b =>
                {
                    b.Property<int>("IdJugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdJugador"));

                    b.Property<int>("Dorsal")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipoIdEquipo")
                        .HasColumnType("integer");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdJugador");

                    b.HasIndex("EquipoIdEquipo");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("GestionTorneos.Partido", b =>
                {
                    b.Property<int>("IdPartido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPartido"));

                    b.Property<int?>("EquipoLocalIdEquipo")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipoVisitanteIdEquipo")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<int>("IdEquipoLocal")
                        .HasColumnType("integer");

                    b.Property<int>("IdEquipoVisitante")
                        .HasColumnType("integer");

                    b.Property<int>("IdTorneo")
                        .HasColumnType("integer");

                    b.Property<int?>("TorneoIdTorneo")
                        .HasColumnType("integer");

                    b.HasKey("IdPartido");

                    b.HasIndex("EquipoLocalIdEquipo");

                    b.HasIndex("EquipoVisitanteIdEquipo");

                    b.HasIndex("TorneoIdTorneo");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("GestionTorneos.Torneo", b =>
                {
                    b.Property<int>("IdTorneo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTorneo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTorneo");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("GestionTorneos.TorneoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipoIdEquipo")
                        .HasColumnType("integer");

                    b.Property<string>("Grupo")
                        .HasColumnType("text");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<int>("IdTorneo")
                        .HasColumnType("integer");

                    b.Property<int?>("TorneoIdTorneo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoIdEquipo");

                    b.HasIndex("TorneoIdTorneo");

                    b.ToTable("TorneosEquipos");
                });

            modelBuilder.Entity("GestionTorneos.EventoJugador", b =>
                {
                    b.HasOne("GestionTorneos.Jugador", "Jugador")
                        .WithMany("Eventos")
                        .HasForeignKey("JugadorIdJugador");

                    b.HasOne("GestionTorneos.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoIdPartido");

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("GestionTorneos.Jugador", b =>
                {
                    b.HasOne("GestionTorneos.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoIdEquipo");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("GestionTorneos.Partido", b =>
                {
                    b.HasOne("GestionTorneos.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalIdEquipo");

                    b.HasOne("GestionTorneos.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteIdEquipo");

                    b.HasOne("GestionTorneos.Torneo", "Torneo")
                        .WithMany("Partidos")
                        .HasForeignKey("TorneoIdTorneo");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("GestionTorneos.TorneoEquipo", b =>
                {
                    b.HasOne("GestionTorneos.Equipo", "Equipo")
                        .WithMany("TorneosEquipos")
                        .HasForeignKey("EquipoIdEquipo");

                    b.HasOne("GestionTorneos.Torneo", "Torneo")
                        .WithMany("TorneosEquipos")
                        .HasForeignKey("TorneoIdTorneo");

                    b.Navigation("Equipo");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("GestionTorneos.Equipo", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("TorneosEquipos");
                });

            modelBuilder.Entity("GestionTorneos.Jugador", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("GestionTorneos.Torneo", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("TorneosEquipos");
                });
#pragma warning restore 612, 618
        }
    }
}
